### ISSUE TITLE
Tried it but got: Failed to fetch dosbox: incompatible OS X version

### ISSUE THREAD

**Issue by aimass** [kencu/macports-ports#2]
Hi,

I tried replacing the port file manually and then got:

Error: dosbox 0.74-3 will not run properly on this version of macOS.
Error: Consider installing dosbox-sdl2 instead.
Error: Failed to fetch dosbox: incompatible OS X version
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_emulators_dosbox/dosbox/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port dosbox failed

Is there any workaround to get DOSbox to run on Catalina 10.15.3

TIA!!
Alex

**Comment by kencu** [comment]
I put that in the portfile to try to steer you to use dosbos-sdl2.

In the directory that contains the portfile, you can do this:

sudo port -v install subport=dosbox-sdl2

please report back. There are a number of people with strong feelings about dosbox, it seems!
